### ISSUE TITLE
Hyperline will not load in 2.0.0-canary.14

### ISSUE THREAD

**Issue by mwdiers** [Hyperline/hyperline#150]
On 2.0.0-canary.14 (latest beta at present), other plugins load fine, but Hyperline will not load.

Attempted to delete ~/.hyper_plugins and restart, but that did not resolve the problem. If I revert to 1.4.8 using the same config, Hyperline loads correctly.

Platform is macOS 10.13.3

Developer Tools console shows:
```
bundle.js:1 (re)loading renderer plugins
bundle.js:1 Plugin hyper-quit (1.0.2) loaded.
bundle.js:1 Plugin hyperterm-paste (1.1.2) loaded.
index.html:35 total init time 205.63
```

**Comment by mwdiers** [comment]
Config as follows:

```
module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 16,

    // font family with optional fallbacks
    fontFamily: '"iosevka-term-medium", "Inconsolata for Powerline", "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    fontWeight: 'normal',

    fontWeightBold: 'normal',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#ccc',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#a70',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: '/opt/homebrew/bin/zsh',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['-i'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false,

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg

    updateChannel: 'canary',

    //Hyperline config
    hyperline: {
        plugins: [
            "hostname",
            "ip",
            "cpu",
            "memory",
            "network",
            "battery"
        ]
    }
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [
    "hyper-quit",
    "hyperline",
    "hyperterm-paste"
  ],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []



};
```

**Comment by chabou** [comment]
@timneutkens @NickTikhonov @timothyis 
More information about this.

From my debug, I think that `hyperline` has never worked with our canary releases.
It is broken from a long time.
Even in v1.4.8, we have an error:
```
{ Error: Cannot find module 'hyper/component'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/chabou/Documents/Projets/hyper/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/chabou/Documents/Projets/hyper/.hyper_plugins/local/hyperline/dist/hyperline.js:79:18)
    at __webpack_require__ (/Users/chabou/Documents/Projets/hyper/.hyper_plugins/local/hyperline/dist/hyperline.js:20:30)
    at Object.<anonymous> (/Users/chabou/Documents/Projets/hyper/.hyper_plugins/local/hyperline/dist/hyperline.js:146:74)
    at __webpack_require__ (/Users/chabou/Documents/Projets/hyper/.hyper_plugins/local/hyperline/dist/hyperline.js:20:30)
    at Object.<anonymous> (/Users/chabou/Documents/Projets/hyper/.hyper_plugins/local/hyperline/dist/hyperline.js:1389:78) code: 'MODULE_NOT_FOUND' }
[Notification] Plugin error!: Plugin "hyperline" failed to load (Cannot find module 'hyper/component')
```

In our v1.X, plugin with error was loaded anyway but not anymore.

This error is due to some `hyper` internals import:
https://github.com/Hyperline/hyperline/blob/246c676c7e29e560dcb513d97fe83cf1166c1737/src/lib/core/hyperline.js#L3-L4
Declared as externals:
https://github.com/Hyperline/hyperline/blob/246c676c7e29e560dcb513d97fe83cf1166c1737/webpack.config.js#L13

I have no idea how it can works lool

Btw, in our next canary (and upcoming v2), `aphrodite` as been replaced by `styled-jsx`. There is no Component superclass anymore in Hyper.

**Comment by goldquest** [comment]
I don't know about canary, but in 1.4.8 the module loading seems to be successfully hijacked: https://github.com/zeit/hyper/blob/1.4.8/lib/utils/plugins.js#L21, but an error is still thrown, which is just a bug, I think.

**Comment by chabou** [comment]
@goldquest thank you to have pointed this out.

The only reason to expose some internals was https://github.com/zeit/hyper/issues/764
But this is not necessary anymore (Component class doesn't exist anymore due to `styled-jsx` migration).

I will try to see if other plugins would be impacted by this removal.

**Comment by chabou** [comment]
@NickTikhonov Any chance to fix this issue soon? Our upcoming v2 is imminent.

**Comment by dakshshah96** [comment]
Doesn't work in 2.0 stable release as well.

**Comment by oshalygin** [comment]
ditto doesn't work in 2.0 stable either.

**Comment by goldquest** [comment]
I'm working on it currently. I replaced aphrodite with styled-jsx, but I still have an issue with the dependence to hyper exposing/hijacking modules.
Either I make a PR for hyper, or we include react and `hyper/component` (which is now just `React.PureComponent`) to this module ourself.

**Comment by oshalygin** [comment]
@goldquest thanks! let me know if you want a hand!

**Comment by goldquest** [comment]
So, I have a working PR. Unfortunately it relies on a fix for hyper itself. Maybe someone can look into that PR, too. 
https://github.com/Hyperline/hyperline/pull/156
https://github.com/zeit/hyper/pull/2866
